/* This file is autogenerated, do not edit*/
#include "moc_detail_widget.cpp"
#include "moc_main_window.cpp"
#include "moc_menu_button.cpp"
#include "moc_menu_widget.cpp"
#include "moc_section.cpp"
#include "moc_setting_item.cpp"
#include "moc_setting_widget.cpp"
